# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: ClusterLabs
email: users@clusterlabs.org
description: Community hub for open-source high-availability software

url: https://www.clusterlabs.org/

# Build settings
theme: minima
destination: ../html
gems:
  - jekyll-assets
  - font-awesome-sass
include:
  - doc
  - pacemaker
  - polls
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE.theme

# All content generated outside of jekyll, or not yet converted to jekyll,
# must be listed here, or jekyll will erase it when building the site.
# Though not documented as such, the values here function as prefix matches.
keep_files:
  - images
  - doc/Two-Stacks.pdf
  - pacemaker/abi
  - pacemaker/doc
  - pacemaker/doxygen
  - pacemaker/global
  - pacemaker/man
