source "https://rubygems.org"
ruby RUBY_VERSION

# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!

# jekyll-assets does not support jekyll 4 yet
gem "jekyll", "~> 3.0"

# This is the default theme for new Jekyll sites. You may change this to anything you like.
gem "minima", "~> 2.0"

# not sure why jekyll doesn't generate this dependency automatically
gem "kramdown-parser-gfm"

# Raise rack dependency version to avoid security issues
gem "rack", ">= 2.2.3.1"

# Needed by jekyll-assets
group :jekyll_assets_deps do
   gem "public_suffix"
   gem "ruby_dep"
   gem "rb-inotify"
   gem "listen"
   gem "jekyll-watch"
   gem "json"
end

# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
   gem "jekyll-assets", "~> 2.0"
   gem "font-awesome-sass"
end
